/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ti_io_BulkRandomAccessFile */

#ifndef _Included_ti_io_BulkRandomAccessFile
#define _Included_ti_io_BulkRandomAccessFile
#ifdef __cplusplus
extern "C" {
#endif
#undef ti_io_BulkRandomAccessFile_O_RDONLY
#define ti_io_BulkRandomAccessFile_O_RDONLY 1L
#undef ti_io_BulkRandomAccessFile_O_RDWR
#define ti_io_BulkRandomAccessFile_O_RDWR 2L
#undef ti_io_BulkRandomAccessFile_O_SYNC
#define ti_io_BulkRandomAccessFile_O_SYNC 4L
#undef ti_io_BulkRandomAccessFile_O_DSYNC
#define ti_io_BulkRandomAccessFile_O_DSYNC 8L
/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([ZII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3ZII
  (JNIEnv *, jobject, jbooleanArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([CII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3CII
  (JNIEnv *, jobject, jcharArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([SII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3SII
  (JNIEnv *, jobject, jshortArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3III
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([JII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3JII
  (JNIEnv *, jobject, jlongArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([FII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3FII
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    readArray0
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_readArray0___3DII
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([ZII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3ZII
  (JNIEnv *, jobject, jbooleanArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([CII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3CII
  (JNIEnv *, jobject, jcharArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([SII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3SII
  (JNIEnv *, jobject, jshortArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3III
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([JII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3JII
  (JNIEnv *, jobject, jlongArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([FII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3FII
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    writeArray0
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_writeArray0___3DII
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     ti_io_BulkRandomAccessFile
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkRandomAccessFile_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
