/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ti_io_BulkDataOutputStream */

#ifndef _Included_ti_io_BulkDataOutputStream
#define _Included_ti_io_BulkDataOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([ZII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3ZII
  (JNIEnv *, jobject, jbooleanArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([CII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3CII
  (JNIEnv *, jobject, jcharArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([SII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3SII
  (JNIEnv *, jobject, jshortArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3III
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([JII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3JII
  (JNIEnv *, jobject, jlongArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([FII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3FII
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    writeArray0
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_writeArray0___3DII
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     ti_io_BulkDataOutputStream
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ti_io_BulkDataOutputStream_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
